import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import { ReactQueryProvider } from "./providers/ReactQueryProvider";

const poppins = Poppins({
  weight: ['200','400','500','600','800'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Repo Hub - Github Repo Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-gray-100`}
      >
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
